-- H2 schema mirroring sql-scripts/userDB.sql for integration / smoke tests.
-- Postgres-only types (inet, jsonb, custom enums) are mapped to H2-friendly equivalents.

CREATE TABLE IF NOT EXISTS user_events (
    event_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       UUID         NOT NULL,
    event_type    VARCHAR(50)  NOT NULL,
    event_data    CLOB         NOT NULL,
    event_version INT          NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_events_user_id ON user_events (user_id);

CREATE TABLE IF NOT EXISTS user_read_model (
    user_id         UUID PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    full_name       VARCHAR(255) NOT NULL,
    role            VARCHAR(50)  NOT NULL,
    password_hash   VARCHAR(255),
    provider        VARCHAR(50)  NOT NULL,
    photo           BYTEA,
    organization_id UUID,
    warehouse_id    UUID,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_email ON user_read_model (email);

CREATE TABLE IF NOT EXISTS login_audit (
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            UUID         NOT NULL,
    login_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address         VARCHAR(64),
    user_agent         VARCHAR(512),
    provider           VARCHAR(50)  NOT NULL,
    refresh_token_hash VARCHAR(60) UNIQUE,
    is_active          BOOLEAN      NOT NULL DEFAULT TRUE,
    logout_at          TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_login_audit_user_id ON login_audit (user_id);
CREATE INDEX IF NOT EXISTS idx_login_audit_refresh_token_hash ON login_audit (refresh_token_hash);

CREATE TABLE IF NOT EXISTS oauth_pending_registrations (
    id              UUID PRIMARY KEY,
    temporary_token VARCHAR(255) NOT NULL UNIQUE,
    email           VARCHAR(255) NOT NULL,
    full_name       VARCHAR(255),
    provider        VARCHAR(20)  NOT NULL,
    provider_uid    VARCHAR(255) NOT NULL,
    photo           BYTEA,
    state_token     VARCHAR(255),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at      TIMESTAMP    NOT NULL,
    completed       BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_oauth_pending_temporary_token ON oauth_pending_registrations (temporary_token);
